In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# patching
import sys
from pathlib import Path
sys.path.insert(0, str(Path.cwd().parent))

from dissertation_gui.protocols.owen.const import Type

In [104]:
data_dir = Path(".").resolve().parent.parent / "data"

In [105]:
df = pd.read_excel(data_dir / "RS-485" / "Owen.xlsx")

In [106]:
df.head(10)

,Наименование \nпараметра,Индекс,Hash-код (в 16-ой \ncис. счисления),Формат представления \nданных,Характеристика,Диапазон значений на приборе,Диапазон значений в сети
0,Группа LvoP Рабочие параметры прибора,NaN,NaN,NaN,NaN,NaN,NaN
1,PV* (опер.),-,B8DF,F24,Измеренное значение входной величины или код о...,Определяется диапазоном измерения датчика,NaN
2,SP*,0,9107,F24,Уставка,определяется параметрами\n SL.L и SL.H,NaN
3,Группа Lvin. Параметры входов прибора,NaN,NaN,NaN,NaN,NaN,NaN
4,in.t,0,E054,T,Тип входного датчика или сигнала,r385 r.385 r391 r.391 r-21 r426 r.426 r-23 r42...,1\n 2\n 3\n 4\n 5\n 6\n 7\n 8\n 9\n 1...
5,dPt,0,37C8,UB,Точность вывода температуры,0.1,NaN
6,dP,0,B3EB,UB,Положение десятичной точки,"0,1,2,3",NaN
7,in.L*,0,FAEE,F24,Нижняя граница измерения диапазона,-1999…9999,NaN
8,in.H*,0,F7B3,F24,Верхняя граница измерения диапазона,-1999…9999,NaN
9,Sqr,0,B465,T,Вычислитель квадратного корня,oFF on,0\n 1

In [107]:
df.rename(
    columns={
        "Наименование \nпараметра": "name",
        "Индекс": "index",
        "Hash-код (в 16-ой \ncис. счисления)": "hash_hex",
        "Формат представления \nданных": "type",
        "Характеристика": "description",
    },
    inplace=True,
)

In [108]:
df = df[(~df["description"].isna()) & (~df["type"].isna())]

In [109]:
df.head()

,name,index,hash_hex,type,description,Диапазон значений на приборе,Диапазон значений в сети
1,PV* (опер.),-,B8DF,F24,Измеренное значение входной величины или код о...,Определяется диапазоном измерения датчика,NaN
2,SP*,0,9107,F24,Уставка,определяется параметрами\n SL.L и SL.H,NaN
4,in.t,0,E054,T,Тип входного датчика или сигнала,r385 r.385 r391 r.391 r-21 r426 r.426 r-23 r42...,1\n 2\n 3\n 4\n 5\n 6\n 7\n 8\n 9\n 1...
5,dPt,0,37C8,UB,Точность вывода температуры,0.1,NaN
6,dP,0,B3EB,UB,Положение десятичной точки,"0,1,2,3",NaN

In [110]:
df["name"] = df["name"].apply(lambda x: x.replace("*","").replace("(опер.)", "").strip(), )

In [111]:
df.head()

,name,index,hash_hex,type,description,Диапазон значений на приборе,Диапазон значений в сети
1,PV,-,B8DF,F24,Измеренное значение входной величины или код о...,Определяется диапазоном измерения датчика,NaN
2,SP,0,9107,F24,Уставка,определяется параметрами\n SL.L и SL.H,NaN
4,in.t,0,E054,T,Тип входного датчика или сигнала,r385 r.385 r391 r.391 r-21 r426 r.426 r-23 r42...,1\n 2\n 3\n 4\n 5\n 6\n 7\n 8\n 9\n 1...
5,dPt,0,37C8,UB,Точность вывода температуры,0.1,NaN
6,dP,0,B3EB,UB,Положение десятичной точки,"0,1,2,3",NaN

In [112]:
df["index"] = df["index"].apply(lambda x: -1 if x == "-" or np.isnan(x) else int(x))

In [113]:
df.head()

,name,index,hash_hex,type,description,Диапазон значений на приборе,Диапазон значений в сети
1,PV,-1,B8DF,F24,Измеренное значение входной величины или код о...,Определяется диапазоном измерения датчика,NaN
2,SP,0,9107,F24,Уставка,определяется параметрами\n SL.L и SL.H,NaN
4,in.t,0,E054,T,Тип входного датчика или сигнала,r385 r.385 r391 r.391 r-21 r426 r.426 r-23 r42...,1\n 2\n 3\n 4\n 5\n 6\n 7\n 8\n 9\n 1...
5,dPt,0,37C8,UB,Точность вывода температуры,0.1,NaN
6,dP,0,B3EB,UB,Положение десятичной точки,"0,1,2,3",NaN

In [114]:
df["hash_hex"] = df["hash_hex"].apply(lambda x: '0x' + str(x).replace("'", ""))

In [115]:
df["hash"] = df["hash_hex"].apply(lambda x: int(x, base=16))

In [116]:
df.head()

,name,index,hash_hex,type,description,Диапазон значений на приборе,Диапазон значений в сети,hash
1,PV,-1,0xB8DF,F24,Измеренное значение входной величины или код о...,Определяется диапазоном измерения датчика,NaN,47327
2,SP,0,0x9107,F24,Уставка,определяется параметрами\n SL.L и SL.H,NaN,37127
4,in.t,0,0xE054,T,Тип входного датчика или сигнала,r385 r.385 r391 r.391 r-21 r426 r.426 r-23 r42...,1\n 2\n 3\n 4\n 5\n 6\n 7\n 8\n 9\n 1...,57428
5,dPt,0,0x37C8,UB,Точность вывода температуры,0.1,NaN,14280
6,dP,0,0xB3EB,UB,Положение десятичной точки,"0,1,2,3",NaN,46059

In [119]:
df["type"] = df["type"].apply(lambda x: Type(x))